# Generated by Django 4.2 on 2023-05-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_country_alter_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_talent',
            field=models.BooleanField(default=False),
        ),
    ]
