# Generated by Django 4.2 on 2023-05-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_country_alter_profile_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_talent',
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('US', 'USER'), ('CO', 'COMPANY')], max_length=512, null=True),
        ),
    ]
