# Generated by Django 4.2 on 2023-05-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('TA', 'TALENT'), ('CO', 'COMPANY')], default='TALENT', max_length=512),
        ),
    ]
