# Generated by Django 4.2 on 2023-06-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_country_profile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
    ]
