# Generated by Django 4.2 on 2023-06-08 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
    ]
