# Generated by Django 4.2 on 2023-04-26 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='salary_lower',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='salary_upper',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
