# Generated by Django 4.2 on 2023-05-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_salary_lower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.AddField(
            model_name='company',
            name='email_company',
            field=models.EmailField(default='User.email', max_length=254, verbose_name='email address'),
        ),
    ]
