# Generated by Django 4.2 on 2023-05-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_comment_likes_company_email_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email_company',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
