# Generated by Django 4.2 on 2023-06-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_profile_date_of_birth'),
        ('projects', '0006_alter_company_company_name_alter_company_country_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Vacancy',
        ),
    ]
