# Generated by Django 4.2 on 2023-06-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_profile_date_of_birth'),
        ('projects', '0010_alter_vacancy_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['date_posted']},
        ),
        migrations.RemoveField(
            model_name='company',
            name='image',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(to='users.skill'),
        ),
    ]
